---
- include: Debian.yml
  when: ansible_os_family == "Debian"
  
- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Create folder(s)
  file: path=/opt/src state=directory owner=root group=root mode=0755

- name: 'Download python {{ python_version }}'
  get_url: url={{ python_package_url }} dest=/opt/src/{{ python_file_name }}

- name: 'Unpack python {{ python_version }}'
  command: tar -xzf {{ python_file_name }} chdir=/opt/src creates=/opt/src/{{ python_file_tag }}

- name: 'Compile and install python {{ python_version }}'
  shell: ./configure --prefix={{ python_path }}/ && make && make altinstall chdir=/opt/src/{{ python_file_tag }} creates={{ python_path }}/bin/python{{ python_base_version }}
  sudo: true
